name: Deploy Frontend

on:
  push:
    paths:
      - 'ai-chatbot-frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm install -g @railway/cli

      - name: Deploy Frontend
        run: |
          cd ai-chatbot-frontend/ai-chatbot-frontend
          railway up --project $RAILWAY_FRONTEND_PROJECT --service frontend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_FRONTEND_PROJECT: ${{ secrets.RAILWAY_FRONTEND_PROJECT }}
